# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_all": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://akashpalrecha.github.io/computational-linear-algebra/"

git_url = "https://github.com/akashpalrecha/computational-linear-algebra/tree/master/"

def custom_doc_links(name): return None
