# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['print_all']

# Cell
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

# Cell
def print_all(*args, **kwargs):
    for arg in args: print(arg)
    for key, value in kwargs.items(): print(f"{key} : {value}")