# AUTOGENERATED! DO NOT EDIT! File to edit: 01_lesson1.ipynb (unless otherwise specified).

__all__ = ['shapes']

# Cell
def shapes(*args, **kwargs):
    """ Prints shapes of all arguments passed on separate lines """
    for arg in args:
        print(arg.shape)
    for key, value in kwargs.items():
        print(f"{key} : {value.shape}")